name: lando-mssql-2022
services:
  defaults:
    type: mssql:2022-latest

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mssql": ./../../
